### ISSUE TITLE
Incompatible with 1.19.3

### ISSUE THREAD

**Issue by MeeniMc** [kyrptonaught/EnchantedToolTips#40]
Here is the error when using the 'shift' key to show the extended tooltip. 

```
---- Minecraft Crash Report ----
// Shall we play a game?
 Time: 2023-01-13 20:04:43
 Description: Rendering screen 
java.lang.NoSuchFieldError: field_11160 	at
net.kyrptonaught.enchantedtooltips.EnchantToolTipHelper.appendEnchantInfo(EnchantToolTipHelper.java:58) 	at 
net.kyrptonaught.enchantedtooltips.EnchantToolTipHelper.appendToolTip(EnchantToolTipHelper.java:37) 	at 
net.minecraft.class_1772.redirect$che000$ETTM$appendTooltip(net/kyrptonaught/enchantedtooltips/mixin/EnchantedBookMixin.java 
[net.kyrptonaught.enchantedtooltips.json]:23) 	at net.minecraft.class_1772.method_7851(class_1772.java:44) 	at 
net.minecraft.class_1799.method_7950(class_1799.java:688) 	at
net.minecraft.class_481.method_25409(class_481.java:756) 	at 
net.minecraft.class_465.method_2380(class_465.java:188) 	at 
net.minecraft.class_481.method_25394(class_481.java:745) 	at 
net.minecraft.class_437.method_47413(class_437.java:113) 	at
net.minecraft.class_757.method_3192(class_757.java:929) 	at 
net.minecraft.class_310.method_1523(class_310.java:1193) 	at
net.minecraft.class_310.method_1514(class_310.java:781) 	at 
net.minecraft.client.main.Main.method_44604(Main.java:244) 	at
net.minecraft.client.main.Main.main(Main.java:51) 	at 
net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) 	at 
net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at 
net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) 	at 
org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) 	at 
org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by Kxsumi** [comment]
NGL dude I think this plugin is just about abandoned

**Comment by kyrptonaught** [comment]
I'm not super active with modding anymore, not completely abandoned though.

I updated this for 1.19.3. Find it on curseforge or modrinth
